if (ASAN_ENABLED)
    add_compile_options(-fsanitize=address,undefined)
    set(CMAKE_EXE_LINKER_FLAGS -fsanitize=address,undefined)
    message(STATUS "Address and Undefined sanitizers enabled")
endif()
